---
- name: Manage HTTPD Service
  hosts: EE1.hsilab.com
  tasks:
   - name: install apache server
     yum:
      name: apache
      state: present
    - name: Ensure httpd service is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

